//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.03 at 08:17:48 PM EST 
//


package com.expr.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}record-id"/>
 *         &lt;element ref="{}defect-number"/>
 *         &lt;element ref="{}summary"/>
 *         &lt;element ref="{}entered-by"/>
 *         &lt;element ref="{}date-entered"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}product"/>
 *         &lt;element ref="{}priority"/>
 *         &lt;element ref="{}severity"/>
 *         &lt;element ref="{}workaround"/>
 *         &lt;element ref="{}custom-field-value"/>
 *         &lt;element ref="{}reported-by-record"/>
 *         &lt;element ref="{}defect-event" maxOccurs="unbounded"/>
 *         &lt;element ref="{}defect-status"/>
 *         &lt;element ref="{}created-by"/>
 *         &lt;element ref="{}date-created"/>
 *         &lt;element ref="{}creation-method"/>
 *         &lt;element ref="{}last-modified-by"/>
 *         &lt;element ref="{}date-last-modified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordId",
    "defectNumber",
    "summary",
    "enteredBy",
    "dateEntered",
    "type",
    "product",
    "priority",
    "severity",
    "workaround",
    "customFieldValue",
    "reportedByRecord",
    "defectEvent",
    "historicalEvent",
    "defectStatus",
    "createdBy",
    "dateCreated",
    "creationMethod",
    "lastModifiedBy",
    "dateLastModified"
})
@XmlRootElement(name = "defect")
public class Defect {

    @XmlElement(name = "record-id", required = true)
    public BigInteger recordId;
    @XmlElement(name = "defect-number", required = true)
    public BigInteger defectNumber;
    @XmlElement(required = true)
    public String summary;
    @XmlElement(name = "entered-by", required = true)
    public EnteredBy enteredBy;
    @XmlElement(name = "date-entered", required = true)
    public String dateEntered;
    @XmlElement(required = true)
    public String type;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    public String product;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    public String priority;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    public String severity;
    @XmlElement(required = true)
    public Workaround workaround;
    @XmlElement(name = "custom-field-value", required = true)
    public List<CustomFieldValue> customFieldValue;
    @XmlElement(name = "reported-by-record", required = true)
    public ReportedByRecord reportedByRecord;
    @XmlElement(name = "defect-event", required = true)
    public List<DefectEvent> defectEvent;
    @XmlElement(name = "historical-event", required = true)
    public List<HistoricalEvent> historicalEvent;
    @XmlElement(name = "defect-status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    public String defectStatus;
    @XmlElement(name = "created-by", required = true)
    public CreatedBy createdBy;
    @XmlElement(name = "date-created", required = true)
    public String dateCreated;
    @XmlElement(name = "creation-method", required = true)
    public String creationMethod;
    @XmlElement(name = "last-modified-by", required = true)
    public LastModifiedBy lastModifiedBy;
    @XmlElement(name = "date-last-modified", required = true)
    public String dateLastModified;

    /**
     * Gets the value of the recordId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordId() {
        return recordId;
    }

    /**
     * Sets the value of the recordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordId(BigInteger value) {
        this.recordId = value;
    }

    /**
     * Gets the value of the defectNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefectNumber() {
        return defectNumber;
    }

    /**
     * Sets the value of the defectNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefectNumber(BigInteger value) {
        this.defectNumber = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the enteredBy property.
     * 
     * @return
     *     possible object is
     *     {@link EnteredBy }
     *     
     */
    public EnteredBy getEnteredBy() {
        return enteredBy;
    }

    /**
     * Sets the value of the enteredBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteredBy }
     *     
     */
    public void setEnteredBy(EnteredBy value) {
        this.enteredBy = value;
    }

    /**
     * Gets the value of the dateEntered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateEntered() {
        return dateEntered;
    }

    /**
     * Sets the value of the dateEntered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateEntered(String value) {
        this.dateEntered = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the workaround property.
     * 
     * @return
     *     possible object is
     *     {@link Workaround }
     *     
     */
    public Workaround getWorkaround() {
        return workaround;
    }

    /**
     * Sets the value of the workaround property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workaround }
     *     
     */
    public void setWorkaround(Workaround value) {
        this.workaround = value;
    }

    /**
     * Gets the value of the customFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldValue }
     *     
     */
    public List<CustomFieldValue> getCustomFieldValue() {
        return customFieldValue;
    }

    /**
     * Sets the value of the customFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldValue }
     *     
     */
    public void setCustomFieldValue(List<CustomFieldValue> value) {
        this.customFieldValue = value;
    }

    /**
     * Gets the value of the reportedByRecord property.
     * 
     * @return
     *     possible object is
     *     {@link ReportedByRecord }
     *     
     */
    public ReportedByRecord getReportedByRecord() {
        return reportedByRecord;
    }

    /**
     * Sets the value of the reportedByRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportedByRecord }
     *     
     */
    public void setReportedByRecord(ReportedByRecord value) {
        this.reportedByRecord = value;
    }

    /**
     * Gets the value of the defectEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defectEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefectEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefectEvent }
     * 
     * 
     */
    public List<DefectEvent> getDefectEvent() {
        if (defectEvent == null) {
            defectEvent = new ArrayList<DefectEvent>();
        }
        return this.defectEvent;
    }

    /**
     * Gets the value of the defectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefectStatus() {
        return defectStatus;
    }

    /**
     * Sets the value of the defectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefectStatus(String value) {
        this.defectStatus = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link CreatedBy }
     *     
     */
    public CreatedBy getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatedBy }
     *     
     */
    public void setCreatedBy(CreatedBy value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationMethod() {
        return creationMethod;
    }

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationMethod(String value) {
        this.creationMethod = value;
    }

    /**
     * Gets the value of the lastModifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link LastModifiedBy }
     *     
     */
    public LastModifiedBy getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * Sets the value of the lastModifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastModifiedBy }
     *     
     */
    public void setLastModifiedBy(LastModifiedBy value) {
        this.lastModifiedBy = value;
    }

    /**
     * Gets the value of the dateLastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastModified() {
        return dateLastModified;
    }

    /**
     * Sets the value of the dateLastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastModified(String value) {
        this.dateLastModified = value;
    }

	public List<HistoricalEvent> getHistoricalEvent() {
		if(historicalEvent  == null)
			historicalEvent = new ArrayList<HistoricalEvent>();
		return historicalEvent;
	}
    
    
}
