//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.03 at 08:17:48 PM EST 
//


package com.expr.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VersionFound_QNAME = new QName("", "version-found");
    private final static QName _RecordId_QNAME = new QName("", "record-id");
    private final static QName _Summary_QNAME = new QName("", "summary");
    private final static QName _Severity_QNAME = new QName("", "severity");
    private final static QName _Product_QNAME = new QName("", "product");
    private final static QName _Notes_QNAME = new QName("", "notes");
    private final static QName _CreationMethod_QNAME = new QName("", "creation-method");
    private final static QName _EventDate_QNAME = new QName("", "event-date");
    private final static QName _DefectNumber_QNAME = new QName("", "defect-number");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Priority_QNAME = new QName("", "priority");
    private final static QName _DefectStatus_QNAME = new QName("", "defect-status");
    private final static QName _FirstName_QNAME = new QName("", "first-name");
    private final static QName _DateLastModified_QNAME = new QName("", "date-last-modified");
    private final static QName _DateFound_QNAME = new QName("", "date-found");
    private final static QName _EventName_QNAME = new QName("", "event-name");
    private final static QName _MiddleName_QNAME = new QName("", "middle-name");
    private final static QName _DateEntered_QNAME = new QName("", "date-entered");
    private final static QName _LastName_QNAME = new QName("", "last-name");
    private final static QName _DateCreated_QNAME = new QName("", "date-created");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StepsToReproduce }
     * 
     */
    public StepsToReproduce createStepsToReproduce() {
        return new StepsToReproduce();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link OtherHardwareAndSoftware }
     * 
     */
    public OtherHardwareAndSoftware createOtherHardwareAndSoftware() {
        return new OtherHardwareAndSoftware();
    }

    /**
     * Create an instance of {@link ReportedByRecord }
     * 
     */
    public ReportedByRecord createReportedByRecord() {
        return new ReportedByRecord();
    }

    /**
     * Create an instance of {@link FoundBy }
     * 
     */
    public FoundBy createFoundBy() {
        return new FoundBy();
    }

    /**
     * Create an instance of {@link ComputerConfig }
     * 
     */
    public ComputerConfig createComputerConfig() {
        return new ComputerConfig();
    }

    /**
     * Create an instance of {@link Workaround }
     * 
     */
    public Workaround createWorkaround() {
        return new Workaround();
    }

    /**
     * Create an instance of {@link EventAuthor }
     * 
     */
    public EventAuthor createEventAuthor() {
        return new EventAuthor();
    }

    /**
     * Create an instance of {@link Defect }
     * 
     */
    public Defect createDefect() {
        return new Defect();
    }

    /**
     * Create an instance of {@link EnteredBy }
     * 
     */
    public EnteredBy createEnteredBy() {
        return new EnteredBy();
    }

    /**
     * Create an instance of {@link CustomFieldValue }
     * 
     */
    public CustomFieldValue createCustomFieldValue() {
        return new CustomFieldValue();
    }

    /**
     * Create an instance of {@link DefectEvent }
     * 
     */
    public DefectEvent createDefectEvent() {
        return new DefectEvent();
    }

    /**
     * Create an instance of {@link EventAssignedTo }
     * 
     */
    public EventAssignedTo createEventAssignedTo() {
        return new EventAssignedTo();
    }

    /**
     * Create an instance of {@link AssignedToUser }
     * 
     */
    public AssignedToUser createAssignedToUser() {
        return new AssignedToUser();
    }

    /**
     * Create an instance of {@link CreatedBy }
     * 
     */
    public CreatedBy createCreatedBy() {
        return new CreatedBy();
    }

    /**
     * Create an instance of {@link LastModifiedBy }
     * 
     */
    public LastModifiedBy createLastModifiedBy() {
        return new LastModifiedBy();
    }

    /**
     * Create an instance of {@link Defects }
     * 
     */
    public Defects createDefects() {
        return new Defects();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version-found")
    public JAXBElement<BigDecimal> createVersionFound(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_VersionFound_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "record-id")
    public JAXBElement<BigInteger> createRecordId(BigInteger value) {
        return new JAXBElement<BigInteger>(_RecordId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSeverity(String value) {
        return new JAXBElement<String>(_Severity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProduct(String value) {
        return new JAXBElement<String>(_Product_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creation-method")
    public JAXBElement<String> createCreationMethod(String value) {
        return new JAXBElement<String>(_CreationMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "event-date")
    public JAXBElement<String> createEventDate(String value) {
        return new JAXBElement<String>(_EventDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defect-number")
    public JAXBElement<BigInteger> createDefectNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_DefectNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPriority(String value) {
        return new JAXBElement<String>(_Priority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defect-status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDefectStatus(String value) {
        return new JAXBElement<String>(_DefectStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first-name")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date-last-modified")
    public JAXBElement<String> createDateLastModified(String value) {
        return new JAXBElement<String>(_DateLastModified_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date-found")
    public JAXBElement<String> createDateFound(String value) {
        return new JAXBElement<String>(_DateFound_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "event-name")
    public JAXBElement<String> createEventName(String value) {
        return new JAXBElement<String>(_EventName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle-name")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date-entered")
    public JAXBElement<String> createDateEntered(String value) {
        return new JAXBElement<String>(_DateEntered_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last-name")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date-created")
    public JAXBElement<String> createDateCreated(String value) {
        return new JAXBElement<String>(_DateCreated_QNAME, String.class, null, value);
    }

}
