//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.03 at 08:17:48 PM EST 
//


package com.expr.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}found-by"/>
 *         &lt;element ref="{}date-found"/>
 *         &lt;element ref="{}version-found"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}steps-to-reproduce"/>
 *         &lt;element ref="{}computer-config"/>
 *         &lt;element ref="{}other-hardware-and-software"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "foundBy",
    "dateFound",
    "versionFound",
    "description",
    "stepsToReproduce",
    "computerConfig",
    "otherHardwareAndSoftware"
})
@XmlRootElement(name = "reported-by-record")
public class ReportedByRecord {

    @XmlElement(name = "found-by", required = true)
    public FoundBy foundBy;
    @XmlElement(name = "date-found", required = true)
    public String dateFound;
    @XmlElement(name = "version-found", required = true)
    public BigDecimal versionFound;
    @XmlElement(required = true)
    public Description description;
    @XmlElement(name = "steps-to-reproduce", required = true)
    public StepsToReproduce stepsToReproduce;
    @XmlElement(name = "computer-config", required = true)
    public ComputerConfig computerConfig;
    @XmlElement(name = "other-hardware-and-software", required = true)
    public OtherHardwareAndSoftware otherHardwareAndSoftware;

    /**
     * Gets the value of the foundBy property.
     * 
     * @return
     *     possible object is
     *     {@link FoundBy }
     *     
     */
    public FoundBy getFoundBy() {
        return foundBy;
    }

    /**
     * Sets the value of the foundBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoundBy }
     *     
     */
    public void setFoundBy(FoundBy value) {
        this.foundBy = value;
    }

    /**
     * Gets the value of the dateFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFound() {
        return dateFound;
    }

    /**
     * Sets the value of the dateFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFound(String value) {
        this.dateFound = value;
    }

    /**
     * Gets the value of the versionFound property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersionFound() {
        return versionFound;
    }

    /**
     * Sets the value of the versionFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersionFound(BigDecimal value) {
        this.versionFound = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the stepsToReproduce property.
     * 
     * @return
     *     possible object is
     *     {@link StepsToReproduce }
     *     
     */
    public StepsToReproduce getStepsToReproduce() {
        return stepsToReproduce;
    }

    /**
     * Sets the value of the stepsToReproduce property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepsToReproduce }
     *     
     */
    public void setStepsToReproduce(StepsToReproduce value) {
        this.stepsToReproduce = value;
    }

    /**
     * Gets the value of the computerConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ComputerConfig }
     *     
     */
    public ComputerConfig getComputerConfig() {
        return computerConfig;
    }

    /**
     * Sets the value of the computerConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComputerConfig }
     *     
     */
    public void setComputerConfig(ComputerConfig value) {
        this.computerConfig = value;
    }

    /**
     * Gets the value of the otherHardwareAndSoftware property.
     * 
     * @return
     *     possible object is
     *     {@link OtherHardwareAndSoftware }
     *     
     */
    public OtherHardwareAndSoftware getOtherHardwareAndSoftware() {
        return otherHardwareAndSoftware;
    }

    /**
     * Sets the value of the otherHardwareAndSoftware property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherHardwareAndSoftware }
     *     
     */
    public void setOtherHardwareAndSoftware(OtherHardwareAndSoftware value) {
        this.otherHardwareAndSoftware = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return description.toString();
	}

}
